language: php

php:
  - 5.5
    env GULP=ON
  - 5.6
    env COVERALLS=ON
  - 7.0
  - nightly

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: travis_ci_twist_test
  username: root
  encoding: utf8

before_install:
   - mysql -V
   - mysql -e "CREATE DATABASE IF NOT EXISTS travis_ci_twist_test;"
   - mysql -e "SHOW DATABASES"
   - if [ "$GULP" = 'ON' ]; then npm install; fi;

install:
  - if [ "$COVERALLS" = 'ON' ]; then composer require satooshi/php-coveralls '~1.0'; fi;
  - composer require phpunit/phpunit:5.6
  - php ./tests/install.php

before_script:
   - mkdir -p ./build/logs
   - mysql -e "USE travis_ci_twist_test; SHOW TABLES;"
   - sed -i 's/Twist::ServeRoutes(false);/echo "TwistPHP Framework Loaded!\n\n";/g' ./tests/index.php

script:
   - phpunit
   - if [ "$GULP" = 'ON' ]; then gulp test; fi;

notifications:
  on_success: never
  on_failure: always

after_success:
   - if [ "$COVERALLS" = 'ON' ]; then ./vendor/bin/coveralls -v; fi;
